### ISSUE TITLE
How does fullTextFields work?

### ISSUE THREAD

**Issue by tolbri** [fox1t/qs-to-mongo#3]
First of all, thank you very much! Your code saved me a lot of time and it works great.

I just cannot figure out how the full text search works. Do you have an example of how the input query should look like?

**Comment by fox1t** [comment]
Hi! The only example you can find is in the tests: https://github.com/fox1t/qs-to-mongo/blob/master/test/q.ts
Basically, it is a matter of passing the fields you want to perform the search on via `fullTextFields` property in the [options](https://github.com/fox1t/qs-to-mongo#options). Then you can invoke the full-text search passing the value to search as the `q` parameter.
