### ISSUE TITLE
Not a function 

### ISSUE THREAD

**Issue by arindam-sworks** [fox1t/qs-to-mongo#4]
TypeError: (0 , qs_to_mongo_1.default) is not a function
I am getting this error. Please resolve this 
import qs2m from 'qs-to-mongo' 
const result = qs2m('name=john&age>21&fields=name,age&sort=name,-age&offset=10&limit=10')

**Comment by fox1t** [comment]
Hey, are you using TypeScript? If so, you should use esModuleInterop to properly import this package. It is a commonjs one.
